const data = [
  {
    id: 1,
    category: "Macaron",
    name: "Macaron mix of five",
    price: 8,
    amount: 1,
    img: "./images/macaron.jpg",
    isInCart: false,
  },
  {
    id: 2,
    category: "Baklava",
    name: "Pistachio Baklava",
    price: 4,
    amount: 1,
    img: "./images/baklava.jpg",
    isInCart: false,
  },
  {
    id: 3,
    category: "Creme Brulee",
    name: "Vanilla Bean Creme Brulee",
    price: 7,
    amount: 1,
    img: "./images/creme.jpg",
    isInCart: false,
  },
  {
    id: 4,
    category: "Tiramisu",
    name: "Classic Tiramisu",
    price: 5.5,
    amount: 1,
    img: "./images/tiramisu.jpg",
    isInCart: false,
  },
  {
    id: 5,
    category: "Cake",
    name: "Red Velvet Cake",
    price: 4.5,
    amount: 1,
    img: "./images/cake.jpg",
    isInCart: false,
  },
  {
    id: 6,
    category: "Brownie",
    name: "Salted Caramel Brownie",
    price: 5.5,
    amount: 1,
    img: "./images/brownie.jpg",
    isInCart: false,
  },
];

export default data;
